### ISSUE TITLE
UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by liaolunhui** [Verizon/helm#11]
Error while importing sbt project:

[info] Loading global plugins from C:\Users\Administrator\.sbt\0.13\plugins
[info] Updating {file:/C:/Users/Administrator/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scala-sbt#sbt;0.13.16 ...
[info] Resolving org.scala-sbt#main;0.13.16 ...
[info] Resolving org.scala-sbt#actions;0.13.16 ...
[info] Resolving org.scala-sbt#classpath;0.13.16 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.16 ...
[info] Resolving org.scala-sbt#io;0.13.16 ...
[info] Resolving org.scala-sbt#control;0.13.16 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.16 ...
[info] Resolving org.scala-sbt#collections;0.13.16 ...
[info] Resolving jline#jline;2.14.4 ...
[info] Resolving org.scala-sbt#api;0.13.16 ...
[info] Resolving org.scala-sbt#classfile;0.13.16 ...
[info] Resolving org.scala-sbt#logging;0.13.16 ...
[info] Resolving org.scala-sbt#process;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.16 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.16 ...
[info] Resolving org.scala-sbt#relation;0.13.16 ...
[info] Resolving org.scala-sbt#compile;0.13.16 ...
[info] Resolving org.scala-sbt#persist;0.13.16 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.16 ...
[info] Resolving org.scala-sbt#ivy;0.13.16 ...
[info] Resolving org.scala-sbt#cross;0.13.16 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.16 ...
[info] Resolving org.scala-sbt#task-system;0.13.16 ...
[info] Resolving org.scala-sbt#tasks;0.13.16 ...
[info] Resolving org.scala-sbt#tracking;0.13.16 ...
[info] Resolving org.scala-sbt#cache;0.13.16 ...
[info] Resolving org.scala-sbt#testing;0.13.16 ...
[info] Resolving org.scala-sbt#test-agent;0.13.16 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.16 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.16 ...
[info] Resolving org.scala-sbt#command;0.13.16 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.16 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from D:\javaProject\my-akka-http-project\project
[info] Updating {file:/D:/javaProject/my-akka-http-project/project/}my-akka-http-project-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
[info] Resolving org.scalariform#sbt-scalariform;1.6.0 ...
[info] Resolving org.scalariform#scalariform_2.10;0.1.8 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving io.spray#sbt-revolver;0.9.1 ...
[info] Resolving org.scala-sbt#sbt;0.13.16 ...
[info] Resolving org.scala-sbt#main;0.13.16 ...
[info] Resolving org.scala-sbt#actions;0.13.16 ...
[info] Resolving org.scala-sbt#classpath;0.13.16 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.16 ...
[info] Resolving org.scala-sbt#io;0.13.16 ...
[info] Resolving org.scala-sbt#control;0.13.16 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.16 ...
[info] Resolving org.scala-sbt#collections;0.13.16 ...
[info] Resolving jline#jline;2.14.4 ...
[info] Resolving org.scala-sbt#api;0.13.16 ...
[info] Resolving org.scala-sbt#classfile;0.13.16 ...
[info] Resolving org.scala-sbt#logging;0.13.16 ...
[info] Resolving org.scala-sbt#process;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.16 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.16 ...
[info] Resolving org.scala-sbt#relation;0.13.16 ...
[info] Resolving org.scala-sbt#compile;0.13.16 ...
[info] Resolving org.scala-sbt#persist;0.13.16 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.16 ...
[info] Resolving org.scala-sbt#ivy;0.13.16 ...
[info] Resolving org.scala-sbt#cross;0.13.16 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.16 ...
[info] Resolving org.scala-sbt#task-system;0.13.16 ...
[info] Resolving org.scala-sbt#tasks;0.13.16 ...
[info] Resolving org.scala-sbt#tracking;0.13.16 ...
[info] Resolving org.scala-sbt#cache;0.13.16 ...
[info] Resolving org.scala-sbt#testing;0.13.16 ...
[info] Resolving org.scala-sbt#test-agent;0.13.16 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.16 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.16 ...
[info] Resolving org.scala-sbt#command;0.13.16 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.16 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to My Akka HTTP Project (in build file:/D:/javaProject/my-akka-http-project/)
>
[info] Defining */*:sbtStructureOptions, */*:sbtStructureOutputFile, *:shellPrompt
[info] The new values will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to My Akka HTTP Project (in build file:/D:/javaProject/my-akka-http-project/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from C:/Users/Administrator/.IntelliJIdea2017.3/config/plugins/Scala/launcher/sbt-structure-0.13.jar
[info] Reapplying settings...
[info] Set current project to My Akka HTTP Project (in build file:/D:/javaProject/my-akka-http-project/)
[info] Updating {file:/D:/javaProject/my-akka-http-project/}root...
[info] Resolving org.scala-lang#scala-library;2.12.5 ...
[info] Resolving com.typesafe.akka#akka-http_2.12;10.1.1 ...
[info] Resolving com.typesafe.akka#akka-http-core_2.12;10.1.1 ...
[info] Resolving com.typesafe.akka#akka-parsing_2.12;10.1.1 ...
[info] Resolving com.typesafe.akka#akka-http-spray-json_2.12;10.1.1 ...
[info] Resolving io.spray#spray-json_2.12;1.3.4 ...
[info] Resolving com.typesafe.akka#akka-http-xml_2.12;10.1.1 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.1.0 ...
[info] Resolving com.typesafe.akka#akka-stream_2.12;2.5.12 ...
[info] Resolving com.typesafe.akka#akka-actor_2.12;2.5.12 ...
[info] Resolving com.typesafe#config;1.3.2 ...
[info] Resolving org.scala-lang.modules#scala-java8-compat_2.12;0.8.0 ...
[info] Resolving com.typesafe.akka#akka-protobuf_2.12;2.5.12 ...
[info] Resolving org.reactivestreams#reactive-streams;1.0.2 ...
[info] Resolving com.typesafe#ssl-config-core_2.12;0.2.3 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.12;1.1.0 ...
[info] Resolving io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1 ...
[info] Resolving io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1 ...
[warn] 	module not found: io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\io.verizon.helm\http4s_2.12\1.4.78-scalaz-7.1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://central.maven.org/maven2/io/verizon/helm/http4s_2.12/1.4.78-scalaz-7.1/http4s_2.12-1.4.78-scalaz-7.1.pom
[warn] ==== ivy-sbt-plugin: tried
[warn]   http://dl.bintray.com/sbt/sbt-plugin-releases/io.verizon.helm/http4s_2.12/1.4.78-scalaz-7.1/ivys/ivy.xml
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/io/verizon/helm/http4s_2.12/1.4.78-scalaz-7.1/http4s_2.12-1.4.78-scalaz-7.1.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/verizon/helm/http4s_2.12/1.4.78-scalaz-7.1/http4s_2.12-1.4.78-scalaz-7.1.pom
[info] Resolving com.typesafe.akka#akka-http-testkit_2.12;10.1.1 ...
[info] Resolving com.typesafe.akka#akka-testkit_2.12;2.5.12 ...
[info] Resolving com.typesafe.akka#akka-stream-testkit_2.12;2.5.12 ...
[info] Resolving org.scalatest#scalatest_2.12;3.0.1 ...
[info] Resolving org.scalactic#scalactic_2.12;3.0.1 ...
[info] Resolving org.scala-lang#scala-reflect;2.12.5 ...
[info] Resolving org.scala-lang#scala-compiler;2.12.5 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
[info] Resolving jline#jline;2.14.5 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.verizon.helm:http4s_2.12:1.4.78-scalaz-7.1 (D:\javaProject\my-akka-http-project\build.sbt#L11)
[warn] 		  +- com.example:my-akka-http-project_2.12:0.1-SNAPSHOT
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: io.verizon.helm#http4s_2.12;1.4.78-scalaz-7.1: not found
[error] Total time: 4 s, completed 2018-4-16 14:35:29
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0

**Comment by rossabaker** [comment]
That's an old version of helm.  helm didn't support Scala 2.12 until version 3.

**Comment by shivamka1** [comment]
It would be nice if README is updated after every release!
