### ISSUE TITLE
Recursive get using ConsulOp.kvGet throwing org.http4s.InvalidMessageBodyFailure exception

### ISSUE THREAD

**Issue by sanjyotb** [Verizon/helm#16]
I wanted to get all nested KeyValues under a prefix path from Consul in single call.
So made the following call (using scala 2.12.6 and http4s 4.0.0):
helm.run(interpreter, ConsulOp.kvGet(key,
    Some(true),
    None,
    Some("/"),
    None,
    None))

**But getting following exception..:**
 
Exception in thread "main" org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: [{"LockIndex":0,"Key":"global/revenue_engine/state_store_configurations/","Flags":0,"Value":null,"CreateIndex":10127650,"ModifyIndex":10127650},
{"LockIndex":0,"Key":"global/revenue_engine/state_store_configurations/firehose_settings","Flags":0,"Value":"dasdsdsad","CreateIndex":10932498,"ModifyIndex":11055277},
{"LockIndex":0,"Key":"global/revenue_engine/state_store_configurations/redis_settings","Flags":0,"Value":"dsadsddf","CreateIndex":10932497,"ModifyIndex":49630384},
{"LockIndex":0,"Key":"global/revenue_engine/state_store_configurations/s3_settings","Flags":0,"Value":"gggfdes","CreateIndex":10932496,"ModifyIndex":11055294}], error: String, cursor: CursorHistory(List(El(CursorOpDownField(Value),true)))
            at org.http4s.argonaut.ArgonautInstances.$anonfun$jsonOf$2(ArgonautInstances.scala:22)

**Comment by aldiyen** [comment]
I think this is fixed by #13 which was just merged in last week. I think @rossabaker may be releasing a new Helm version relatively with that fix in it soon, but you could try compiling the latest version of `master` to see if that fixes your problem.

**Comment by sanjyotb** [comment]
ok. yes, it fixed the problem using latest version of master..
thanks!!
