### ISSUE TITLE
consul watches

### ISSUE THREAD

**Issue by mazorigal** [Verizon/helm#8]
Hi,

does the scala client support:
https://www.consul.io/docs/agent/watches.html ?
https://github.com/OrbitzWorldwide/consul-client#example-4-blocking-call-for-value
My use case is that the app need to get notification via the consul key-value, and act according to a new value of the watched key.

Thanks,

**Comment by aldiyen** [comment]
Hey I'm working on some changes to support blocking calls, so assuming my PR is accepted this should be implemented in the next few weeks (hopefully).

**Comment by Dr-Nikson** [comment]
So.. Is there any ways to watch for consul KV-updates with helm nowadays?

**Comment by aldiyen** [comment]
@Dr-Nikson hey sorry, I saw this while busy and then forgot to reply. Yeah, if you specify the optional `maxWait` parameter then the Consul API call will include the `wait` parameter, causing the API call to block for some amount of time waiting for updates.

This project has moved over to https://github.com/getnelson/helm at this point, just FYI. Maybe @rossabaker or @timperrett could update the README here to indicate that?

**Comment by rossabaker** [comment]
I no longer have write access to this repo.  We can submit a PR to do that, but someone still in the Verizon org will have to notice it and merge it.

**Comment by timperrett** [comment]
+1 on not having access. If you wanted to re-issue the PR against the getnelson/helm repo, we can cut a release with the support

**Comment by aldiyen** [comment]
This change was made in 2017, so it's already in the getnelson/helm version. I just meant updating the README here so people know where to go for the official Helm version rather than looking here. Last I looked, the Consul website also still linked here rather than the getnelson URL.
